### ISSUE TITLE
Question about the inference/infer_t5.py 

### ISSUE THREAD

**Issue by ZhaozwTD** [liujch1998/GKP#1]
Hello, I have a problem with line 58 in inference/infer_t5.py
```
if args.task == 'csqa2' and args.model_ckpt is None:
    scores[1] += 7 
```

I don't quite understand the purpose of this command line, and the choice of the number 7. Why this operation is only employed in the csqa2 dataset?

Many thanks for your nice codes!

**Comment by liujch1998** [comment]
Hi, thanks for noticing this! It's part of the explorative code we left behind and was not used in our final experiments. The purpose was to (manually) calibrate the off-the-shelf LM. I will remove these lines to avoid confusion.
