### ISSUE TITLE
The accuracy in CSQA 2.0

### ISSUE THREAD

**Issue by BAOOOOOM** [liujch1998/GKP#3]
I reproduce the program in CSQA2.0, but the result shows the model predicts "yes" all the time. So the score of CSQA2.0 in my experiment is just about 50% which is is far lower than the performance in your paper.
And I ran the program according to the instructions:

CUDA_VISIBLE_DEVICES=0 python inference/infer_t5.py \
    --task csqa2 \
    --model-type allenai/unifiedqa-t5-3b \
    --input-path data/csqa2/knowledge/context_gpt3.dev.csqa2.json

Can you find the reason of it? Thank you very much.

**Comment by liujch1998** [comment]
Hello. There might be a few reasons: 

1. UnifiedQA-3b might not perform good on CSQA 2.0. We used UNICORN as the inference model for this task. 
2. The knowledge from random text continuation (i.e. `context_gpt3.dev.csqa2.json`) might be of poor quality. Please consider using `knowledge_gpt3.dev.csqa2.json` instead. 

Hope that helps!

**Comment by BAOOOOOM** [comment]
Thanks，the result of using _knowledge_gpt3.dev.csqa2.json_ is better than before!
 But the code in infer_t5.py hasn't the choice of UNICORN, it just has these choices:
['t5-small', 't5-base', 't5-large', 't5-3b', 't5-11b', 'allenai/unifiedqa-t5-large', 'allenai/unifiedqa-t5-3b', 'allenai/unifiedqa-t5-11b']
Can you help me to use UNICORN, thanks!

**Comment by eyuansu62** [comment]
@BAOOOOOM Hi, do you use UNICORN successfully?
Actually, I face the same problem. :)

**Comment by BAOOOOOM** [comment]
> @BAOOOOOM Hi, do you use UNICORN successfully? Actually, I face the same problem. :)

The weight of UNICORN is trained by tensorflow, so it cannot be used in this program directly.
